### ISSUE TITLE
Lets Encrypt

### ISSUE THREAD

**Issue by Cheesman97** [Apache-Labor/labor#12]
Vorschlage zu labor-03 (https)
Wie wäre es mit einer Anleitung zu "Let's Encrypt"?
https://letsencrypt.org/

Gruess
Luca

P.S. die Version 2.4.20 ist draussen ;). Die Angaben stimmen nicht mehr überall.

**Comment by dune73** [comment]
On Mon, Jul 11, 2016 at 12:16:45PM -0700, Luca Käser wrote:

> Vorschlage zu labor-03 (https)
> Wie wäre es mit einer Anleitung zu "Let's Encrypt"?
> https://letsencrypt.org/
> 
> Gruess
> Luca
> 
> P.S. die Version 2.4.20 ist draussen ;). Die Angaben stimmen nicht mehr überall.

Ja, ich möchte Let's Encrypt gerne beschreiben. Ist ein Zeitproblem. :(

Lust mir dabei zu helfen?

2.4.23 (!) habe ich bereits getestet und die Sachen laufen alle noch. 
Muss es einfach updaten. Pull Request welcome.

Ahoj,

Christian

## 

It is our responsibilities, not ourselves, that we should take
seriously.
-- Peter Ustinov

**Comment by Cheesman97** [comment]
Eine erste Version meiner Anleitung habe ich in einem separaten File eingegeben. Teilweise stimmen Pfade oder ähnliches nicht mit der "Schulungsumfang" überein.

**Comment by dune73** [comment]
Sehr schön. Vielen Dank. Schaue ich mir gerne an.

#13

**Comment by Cheesman97** [comment]
#17 
So. Habe nun einen separate PullRequest erstellt.

**Comment by dune73** [comment]
Closing in favor of pull request #17.
