### ISSUE TITLE
Describe custom dhparams configuration

### ISSUE THREAD

**Issue by karras** [Apache-Labor/labor#21]
I'd like to add a short description about custom dhparams and how they could be configured in lab 04. Is this something that was excluded on purpose to keep it simple or can I go ahead and make a proposal?

**Comment by dune73** [comment]
That would be lab 03, would not it?

I tried to keep it simple, but dhparams have grown into a standard thing, so adding this might be a good idea. How much text would you want to write. Also: This means that the English ones need to be updated too. Effectively doubling the work for you - or for me. :)

**Comment by dune73** [comment]
Closing this. Not really a focus of my tutorials and mostly solved in distros these days.
