### ISSUE TITLE
`lastrequestsummary` not functioning as expected

### ISSUE THREAD

**Issue by Xhoenix** [Apache-Labor/labor#25]
In `lastrequestsummary`, the regex `" [a-zA-Z0-9@_-]{24,27} "` needs to adjusted to `"[a-zA-Z0-9@_-]{24,27}"`. The preceeding and succeeding whitespaces needs to be removed.

Ref:- https://github.com/Apache-Labor/labor/blob/23a5bd0a7b975a31abde9849cc9da7c6b507e634/bin/lastrequestsummary#L32

**Comment by Xhoenix** [comment]
![image](https://github.com/Apache-Labor/labor/assets/86168235/2e17b925-5c1b-4518-aee4-f618fa62a2cf)

**Comment by dune73** [comment]
Why?

Also: This is a very outdated repo. But the said script is up to date.

**Comment by Xhoenix** [comment]
I also wondered how can there be such a **script breaking** mistake, when others are working fine. Can you check the regex as I mentioned above?

**Comment by dune73** [comment]
The script does `echo "$ACCESSLINE"`, while your example does something along the line of `echo $UNIQUE_ID`.

Within the access-line, the unique-id is embedded between two spaces. So the original regex works. The one you use could also hit certain URIs, it is therefore weaker and brings no benefit.

Or do I get this wrong?

**Comment by Xhoenix** [comment]
Not sure, but I doubt that's where my test has the issue. Going to check tomorrow and report back. 👍

**Comment by dune73** [comment]
Please do.

**Comment by Xhoenix** [comment]
Cool. The issue was with how I did the test. I should've checked the "ID" variable which strips spaces.
