### ISSUE TITLE
bin/parse-apache-logs.rb fails with GEOIP ASN/ASORG Info

### ISSUE THREAD

**Issue by logopk** [Apache-Labor/labor#26]
Hi @dune73 ,

I'm getting parse errors when analyzing the access log with the new extended format from

https://www.netnea.com/cms/2022/10/12/using-geoip-information-together-with-modsecurity/

tail -n 100  access_modsec.log |parse-apache-logs.rb 
```
...
Problems parsing line 100. Ignoring line. (Error )
93.204.14.xx DE;3320;Deutsche_Telekom_AG - [2024-01-07 12:30:31.403375] "GET / HTTP/2.0" 200 18 "-" "blackbox-monitoring" "-" 42840 mydomain.com 172.18.0.3 443 - - - "ReqID--" ZZqLV_2MpEDR9RfOJkEarwAAxwI TLSv1.3 TLS_AES_256_GCM_SHA384 42 946 -% 11306 5717 0 962 - - 0 0
```

It's running fine without ";ASN;ASORG".

Unfortunately I'm not speaking Ruby, so I'm unable to get deeper into the source of the problem.

Any idea?

Thanks.

Peter

**Comment by dune73** [comment]
Hi Peter,

Thank you for writing in.

Your message reminds me that the geoIP implementation is still an experiment
and that I never really integrated it into the full curriculum.

I know there are are thousands of readers of the Apache / ModSec tutorials
every month, but very, very little feedback.

So yes, this does not really work with the parse script. But it's nice
nevertheless. And I do not use th parse script very much to be honest.
I stick to the extended aliases most of the time and they do have geoIP
coverage.

Best,

Christian
